//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoesProperties.Localize {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en_GB {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_GB() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DominoesProperties.Localize.Resources.en-GB", typeof(Resources_en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Customer_Registration_Subject {
            get {
                return ResourceManager.GetString("Customer.Registration.Subject", resourceCulture);
            }
        }
        
        internal static string Auth_Token_Expired {
            get {
                return ResourceManager.GetString("Auth.Token.Expired", resourceCulture);
            }
        }
        
        internal static string Auth_Link_Generated {
            get {
                return ResourceManager.GetString("Auth.Link.Generated", resourceCulture);
            }
        }
        
        internal static string Password_Error {
            get {
                return ResourceManager.GetString("Password.Error", resourceCulture);
            }
        }
        
        internal static string Username_Error {
            get {
                return ResourceManager.GetString("Username.Error", resourceCulture);
            }
        }
    }
}
