//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoesProperties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerController_en_GB {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerController_en_GB() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DominoesProperties.CustomerController.en-GB", typeof(CustomerController_en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Response_Success {
            get {
                return ResourceManager.GetString("Response.Success", resourceCulture);
            }
        }
        
        internal static string Response_Created {
            get {
                return ResourceManager.GetString("Response.Created", resourceCulture);
            }
        }
        
        internal static string Customer_Registration_Subject {
            get {
                return ResourceManager.GetString("Customer.Registration.Subject", resourceCulture);
            }
        }
        
        internal static string Auth_Token_Expired {
            get {
                return ResourceManager.GetString("Auth.Token.Expired", resourceCulture);
            }
        }
        
        internal static string Auth_Link_Generated {
            get {
                return ResourceManager.GetString("Auth.Link.Generated", resourceCulture);
            }
        }
        
        internal static string Password_Error {
            get {
                return ResourceManager.GetString("Password.Error", resourceCulture);
            }
        }
        
        internal static string Username_Error {
            get {
                return ResourceManager.GetString("Username.Error", resourceCulture);
            }
        }
        
        internal static string Property_Id_Error {
            get {
                return ResourceManager.GetString("Property.Id.Error", resourceCulture);
            }
        }
        
        internal static string Customer_NotVerified {
            get {
                return ResourceManager.GetString("Customer.NotVerified", resourceCulture);
            }
        }
        
        internal static string Response_Customer_Activated {
            get {
                return ResourceManager.GetString("Response.Customer.Activated", resourceCulture);
            }
        }
        
        internal static string Response_Customer_Password_Link {
            get {
                return ResourceManager.GetString("Response.Customer.Password.Link", resourceCulture);
            }
        }
        
        internal static string Response_Customer_Password_Reset {
            get {
                return ResourceManager.GetString("Response.Customer.Password.Reset", resourceCulture);
            }
        }
        
        internal static string Response_Customer_Password_Invalid {
            get {
                return ResourceManager.GetString("Response.Customer.Password.Invalid", resourceCulture);
            }
        }
        
        internal static string No_Content_Found {
            get {
                return ResourceManager.GetString("No.Content.Found", resourceCulture);
            }
        }
    }
}
